### ISSUE TITLE
Add PowerPC support

### ISSUE THREAD

**Issue by barracuda156** [lfreist/hwinfo#26]
Apparently the code currently covers only Intel platforms. Possible to add support for POWER (for *BSD and AIX) and PowerPC (for Apple)?

**Comment by lfreist** [comment]
Hi,
hwinfo should work architecture independent on Linux, Windows and Mac (development for MacOS is not very far...).

The supported (and yet unsupported) features for each platform stated [here](https://github.com/lfreist/hwinfo#supported-components-and-api) should work on any architecture.

Have you already tried building and running hwinfo on a PowerPC?

If so, it would be nice, if you can provide further information on whats unexpected/not working.

**Comment by barracuda156** [comment]
@lfreist I will try and update you.

**Comment by lfreist** [comment]
Closed due to inactivity

**Comment by barracuda156** [comment]
> Closed due to inactivity

I apologize, this went forgotten. I will do this today.

**Comment by barracuda156** [comment]
@lfreist Build fails here for me:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-ce1d868a7c451c27e98614dce74540aea914afd5/src/apple/cpu.cpp: In static member function 'static std::string hwinfo::CPU::getModelName()':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-ce1d868a7c451c27e98614dce74540aea914afd5/src/apple/cpu.cpp:81:22: error: 'model' was not declared in this scope; did you mean 'modfl'?
   81 |   return std::string(model);
      |                      ^~~~~
      |                      modfl
```

**Comment by barracuda156** [comment]
Types of PPC cpus can be found in `/usr/include/mach/machine.h`.
This is how it can be determined: https://www.eidos.ic.i.u-tokyo.ac.jp/~tau/lecture/parallel_distributed/2016/examples/09mm/OpenBLAS/cpuid_power.c

**Comment by lfreist** [comment]
Thank you! It's a pure failure from my side. Didn't have a non x86 Mac for testing thins peace of code... However, I found the bug and will fix it later.

**Comment by barracuda156** [comment]
@lfreist Great, thank you!

**Comment by lfreist** [comment]
commit ba3ba8b165502f1ab979204c4adcf93bb339c5b1 should fix the stated issue. Since I cannot test for non x86 MacOS, I cannot assure that there are no other issues... Would be grateful, if you can provide further information after testing the new commit!

**Comment by barracuda156** [comment]
@lfreist Thank you. There is this error then:
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-ba3ba8b165502f1ab979204c4adcf93bb339c5b1/src/apple/cpu.cpp: In static member function 'static std::string hwinfo::CPU::getModelName()':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-ba3ba8b165502f1ab979204c4adcf93bb339c5b1/src/apple/cpu.cpp:79:58: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
   79 |   if (sysctlbyname("machdep.cpu.brand_string", model.data(), &size, NULL, 0) < 0) {
      |                                                ~~~~~~~~~~^~
      |                                                          |
      |                                                          const void*
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_hwinfo/hwinfo/work/hwinfo-ba3ba8b165502f1ab979204c4adcf93bb339c5b1/src/apple/cpu.cpp:12:
/usr/include/sys/sysctl.h:752:36: note:   initializing argument 2 of 'int sysctlbyname(const char*, void*, size_t*, void*, size_t)'
  752 | int     sysctlbyname(const char *, void *, size_t *, void *, size_t);
      |                                    ^~~~~~
```
When passing `-fpermissive`, it builds through completion. Many objects have no symbols though:
```
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(filesystem.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(battery.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(cpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(gpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(ram.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(os.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(mainboard.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(disk.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(filesystem.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(cpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(gpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(ram.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(os.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(mainboard.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(disk.cpp.o) has no symbols
/opt/local/bin/ranlib ../lib/libHWinfo.a
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(filesystem.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(battery.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(cpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(gpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(ram.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(os.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(mainboard.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(disk.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(filesystem.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(cpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(gpu.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(ram.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(os.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(mainboard.cpp.o) has no symbols
/opt/local/bin/ranlib: file: ../lib/libHWinfo.a(disk.cpp.o) has no symbols
```
Destroot does not work too, but that is trivial to fix on our end.

**Comment by barracuda156** [comment]
@lfreist Okay, I have finally returned to this, and current status is decent: with two minimal fixes (see PR) it builds, 100% of tests pass, and the app display some info. However, there is info which is certainly accessible, but it is not found, and some info is wrong.

```
----------------------------------- CPU ------------------------------------
Socket -1:
vendor:              <unknown>
model:               <unknown>
physical cores:      4
logical cores:       4
max frequency:       2500
regular frequency:   2500
cache size:          L1: 32768, L2: 1048576, L3: -1
                     Thread 0: 2500 MHz (32.071551466566305%)
                     Thread 1: 2500 MHz (31.892921049331903%)
                     Thread 2: 2500 MHz (32.36547920504146%)
                     Thread 3: 2500 MHz (31.95447154210793%)
----------------------------------- OS ------------------------------------
Operating System:    macOS
version:             <unknown>
kernel:              Darwin 10.8.0
architecture:        64 bit
endianess:           big endian
----------------------------------- GPU -----------------------------------
----------------------------------- RAM -----------------------------------
size [MiB]:          0
free [MiB]:          4095.9999990463257
available [MiB]:     4095.9999990463257
RAM 0:
vendor:              <unknown>
model:               <unknown>
name:                <unknown>
serial-number:       <unknown>
Frequency [MHz]:     -1
```

I am not sure what “vendor” should be (IBM? Apple?), but I expect to see PowerPC somewhere. This is detectable.
Also macOS version is not detected, despite the kernel being detected correctly (but there is 1 to 1 mapping from darwin versions to macOS versions).

**Comment by barracuda156** [comment]
@lfreist Update when building the app from 64bc6ea98518d2964443bb1104cde90e9e031820 – 

```
Thanks for using hwinfo!

Hardware Report:

----------------------------------- CPU ------------------------------------
Socket -1:
vendor:              <unknown>
model:               <unknown>
physical cores:      4
logical cores:       4
max frequency:       2500
regular frequency:   2500
cache size:          L1: 32768, L2: 1048576, L3: -1
                     Thread 0: 2500 MHz (22.86846169341301%)
                     Thread 1: 2500 MHz (24.01860313243921%)
                     Thread 2: 2500 MHz (23.297006032966085%)
                     Thread 3: 2500 MHz (24.016158227009843%)
----------------------------------- OS ------------------------------------
Operating System:    macOS
version:             <unknown> (10K549)
kernel:              Darwin 10.8.0
architecture:        64 bit
endianess:           big endian
----------------------------------- GPU -----------------------------------
----------------------------------- RAM -----------------------------------
size [MiB]:          0
free [MiB]:          4095.9999990463257
available [MiB]:     4095.9999990463257
RAM 0:
vendor:              <unknown>
model:               <unknown>
name:                <unknown>
serial-number:       <unknown>
Frequency [MHz]:     -1
------------------------------- Main Board --------------------------------
vendor:              <unknown>
name:                <unknown>
version:             <unknown>
serial-number:       YM54545ZR6W
------------------------------- Batteries ---------------------------------
No Batteries installed or detected
--------------------------------- Disks -----------------------------------
Disk 0:
vendor:              <unknown>
model:               WDC WD2500JS-41MVB1 WDC WD2500JS-41MVB1
serial-number:       <unknown>
size:                250059350016
free:                8755404800
volumes:             /
Disk 1:
vendor:              <unknown>
model:               VO0600ECHPP VO0600ECHPP
serial-number:       <unknown>
size:                600127266816
free:                25035939840
volumes:             /Volumes/Snow_SSD
--------------------------------- Networks -----------------------------------
No Networks installed or detected
```

There are definite improvements, but OS version is still missing (10.6.8), only build version is detected; RAM amount is incorrect (16 GB in fact on this machine); for architecture I would expect to see the actual architecture, not bitness (and even if bitness, then bitness of OS, not physical CPU – the latter is of little help, if OS bitness differs).

**Comment by Shieldine** [comment]
By the way, there is currently no actual check for 32/64 bit. We currently just say everything is 64 bit. We should probably add a check in the future.

**Comment by barracuda156** [comment]
@Shieldine Could you point to the code which is responsible for what does not work correctly now? I will see if I can adapt what `fastfetch` uses or what I added to it to make it actually work.

**Comment by lfreist** [comment]
I currently have no MacOS at all, so I can't be of any programming related help. However, I'd be happy to help with design decisions and code structure etc! Thank you both for the effort in making HWInfo work on MacOS!
